### ISSUE TITLE
fyne的实战

### ISSUE THREAD

**Issue by 63isOK** [63isOK/plan#66]
- [ ] 无边框处理
- [ ] 贴图,或是颜色处理
- [ ] windows dpi

**Comment by 63isOK** [comment]
fyne还缺失很多基础功能,最重要是开发团队不愿意添加这些功能

**Comment by michelia** [comment]
![xx](https://user-images.githubusercontent.com/1680468/100869498-197af180-34d8-11eb-942f-22580ae06541.png)
请问怎么用fyne做这种UI风格客户端？

**Comment by 63isOK** [comment]
@michelia  建议使用flutter
